#!/usr/bin/env sh
# Script to backup /home/data and /home to the external hard drive that is hopefully attached

DEBUG_FLAG=
DEBUG="$1"

[[ "$DEBUG" = "-d" ]] && DEBUG_FLAG="nv"

#check that mountpoint exists
[ -d /mnt/ext_hd ] || { echo "Mountpoint doesn't exist" && exit 1; }

#check that it is mounted by looking for backup folder
[ -d /mnt/ext_hd/backup ] || { echo "External HD probably not mounted" && exit 1; }

#DATA DRIVE
#define source and target for
SOURCE=/home/data/
DESTINATION=/mnt/ext_hd/backup/data/

#make destination directory if not existant
[ -d $DESTINATION ] && mkdir -p $DESTINATION

echo "Starting backup of /home/data"
( rsync -ar$DEBUG_FLAG --exclude '*.pic' $SOURCE $DESTINATION && echo "Successfully backuped data" ) || echo "Couldn't successfully backup data directory"

#HOME DRIVE
unset SOURCE
unset DESTINATION
SOURCE="/home/lukas/code /home/lukas/Documents /home/lukas/.config"
DESTINATION=/mnt/ext_hd/backup/home

#make destination directory if necessary
[ -d $DESTINATION ] && mkdir -p $DESTINATION

echo "Starting backup of home directory"
(rsync -ar$DEBUG_FLAG --no-links --exclude '*.pic' $SOURCE $DESTINATION && echo "Successfully backuped home dir") || echo "Couldn't successfully backup home directory"
